// AUTO-GENERATED by scripts/import-adapter.mjs
// Importing each adapter triggers its top-level cli({...}) registration.

import './comment-create.js';
import './comments.js';
import './creator-note-detail.js';
import './creator-notes-summary.js';
import './creator-notes.js';
import './creator-profile.js';
import './creator-stats.js';
import './download.js';
import './feed.js';
import './note.js';
import './notifications.js';
import './publish.js';
import './search.js';
import './user.js';
